export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const SET_NEXT_PHOTO = 'SET_NEXT_PHOTO';
export const SET_PREVIOUS_PHOTO = 'SET_PREVIOUS_PHOTO';
export const TOGGLE_AUTHENTICATED_STATUS = 'TOGGLE_AUTHENTICATED_STATUS';
export const TOGGLE_ADMIN_STATUS = 'TOGGLE_ADMIN_STATUS';